image: maven:3.5.2
buildTool: maven
branches:
  - master
env:
  - "MARIANNE=1"
stages:
   - name: build
     script:
        - mvn clean install
   - name: testt
     script:
        - echo "WOOOOEEE I AM TESTING!!!!"