image: jessishank/mavendocker
buildTool: maven
branches:
- master
notify:
  slack:
    identifier: "L11_SLACK"
    on:
    - "FAIL"
    - "PASS"
stages:
   - name: echo
     triggers:
      - \branch master || develop and \filepath ocelot.yml
     script:
        - echo "using new triggers"
        - echo "$GIT_PREVIOUS_SUCCESSFUL_COMMIT"
   - name: build
     script:
        - mvn clean install
   - name: echoshit
     script: 
      - echo "OH HEEEEYYYYY I'M ECHOING _SO_ HARD RN!"
   - name: build
     script:
        - docker build .
   - name: moretestystuffy
     script:
        - echo "ugh everyhting is hard"


