image: jessishank/mavendocker
buildTool: maven
branches:
- master
env:
  - "MARIANNE=1"
  - |-
        multiline=hi
        lorem
        ipsum
stages:
  - name: echo
    script: 
      - echo $multiline
   - name: build
     script:
        - mvn clean install
   - name: echoshit
     script: 
      - echo "OH HEEEEYYYYY I'M ECHOING _SO_ HARD RN!"
   - name: build
     script:
        - docker build .
   - name: moretestystuffy
     script:
        - echo "ugh everyhting is hard"


