image: jessishank/mavendocker
buildTool: maven
branches:
- master
env:
  - "MARIANNE=1"
  - |-
        multiline=hi
        lorem
        ipsum
stages:
   - name: wtfd
     env: 
      - "ayyyyy=~/.m2/settings.xml"
     script: 
        - cat "$ayyyyy"
        - echo $ayyyyy
        - cat ~/.m2/settings.xml
        - echo "$GIT_HASH_SHORT"
   - name: skipme
     trigger:
       branches: 
         - skippppero
     script: 
      - dis be a nice scripty
   - name: echo
     script:
        - echo $HI
        - echo $WOOPS
   - name: build
     script:
        - mvn clean install
   - name: echoshit
     script: 
      - echo "OH HEEEEYYYYY I'M ECHOING _SO_ HARD RN!"
   - name: build
     script:
        - docker build .
   - name: moretestystuffy
     script:
        - echo "ugh everyhting is hard"


