image: jessishank/mavendocker
buildTool: maven
branches:
  - master
env:
  - "MARIANNE=1"
stages:
   - name: build
     script:
        - mvn clean install
   - name: testt
     script:
        - docker build .


