image: jessishank/mavendocker
buildTool: maven
branches:
- master
notify:
  slack:
    identifier: "slack"
    on:
    - "FAIL"
    - "PASS"
env:
  - "MARIANNE=1"
  - |-
        multiline=hi
        lorem
        ipsum
stages:
   - name: helm  my boyyyyyyyyyyy
     script:
      - helm search test/
   - name: skipme
     triggers:
      - \branch skippppero 
     script: 
      - dis be a nice scripty
   - name: echo
     triggers:
      - \branch master||develop and \text testing
     script:
        - echo $HI
        - echo $WOOPS
   - name: build
     script:
        - mvn clean install
   - name: echoshit
     script: 
      - echo "OH HEEEEYYYYY I'M ECHOING _SO_ HARD RN!"
   - name: build
     script:
        - docker build .
   - name: moretestystuffy
     script:
        - echo "ugh everyhting is hard"


